book/urls.py
from django import views
from django.urls import path, include
from book.views import get_books_by_json, get_books_by_xml, register, login_user, logout_user, show_main, search, get_product_json

app_name = 'book'

urlpatterns = [
    path('json/', get_books_by_json, name='get_book_by_jsons'),
    path('xml/', get_books_by_xml, name='get_by_xml'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='searchbar'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('review/', include("review.urls")),
]

mutualibri/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("book.urls")),
    path('', include("lend.urls")),
    path('review/', include("review.urls")),
    path('quote/', include("quote.urls")),
    path('auth/', include('authentication.urls')),
]

quote/urls.py
from django.urls import path
from quote.views import create_product_flutter, quotes_page, add_quote, edit_quote, delete_quote, show_json, show_json_by_id, add_quote_ajax\
, get_quote

app_name = 'quote'

urlpatterns = [
    path('', quotes_page, name='quotes_page'),
    path('add-quote', add_quote, name='add_quote'),
    path('edit-quote/<int:id>/', edit_quote, name='edit_quote'),
    path('delete-quote/<int:id>/', delete_quote, name='delete_quote'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('get-quote/', get_quote, name='get_quote'),
    path('add-quote-ajax/', add_quote_ajax, name='add_quote_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

quote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Quotes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.TextField(null=True)
    book_name = models.CharField(max_length=255)
    quotes = models.TextField(max_length=255)

quote/forms.py
from django.forms import ModelForm
from quote.models import Quotes

class QuoteForm(ModelForm):
    class Meta:
        model = Quotes
        fields = ["book_name", "quotes"]

quote/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from quote.forms import QuoteForm
from django.urls import reverse
from quote.models import Quotes
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def quotes_page(request):
    sort_order = request.GET.get('sort_order', 'recent')  # Defaultnya, urutkan berdasarkan yang terbaru

    if sort_order == 'recent':
        quotes = Quotes.objects.all().order_by('-id')  # Urutkan berdasarkan yang terbaru (default)
    else:
        quotes = Quotes.objects.all().order_by('id')  # Urutkan berdasarkan yang terlama

    context = {
        'name': "nama",
        'quotes': quotes,
        'sort_order': sort_order,
    }

    return render(request, "quotes.html", context)

def add_quote(request):
    form = QuoteForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        quote = form.save(commit=False)
        quote.user = request.user
        quote.username = request.user.username
        quote.save()
        return HttpResponseRedirect(reverse('quote:quotes_page'))

    context = {'form': form}
    return render(request, "add_quote.html", context)


def edit_quote(request, id):
    quote = Quotes.objects.get(pk = id)
    form = QuoteForm(request.POST or None, instance=quote)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('quote:quotes_page'))
    
    context = {'form': form}
    return render(request, "edit_quote.html", context)
    
def delete_quote(request, id):
    quote = Quotes.objects.filter(pk=id)
    quote.delete()

    return redirect('quote:quotes_page')

def show_json(request):
    data = Quotes.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Quotes.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_quote(request):
    quotes = Quotes.objects.all()
    return HttpResponse(serializers.serialize('json', quotes))

@csrf_exempt
def add_quote_ajax(request):
    if request.method == 'POST':
        book_name = request.POST.get("book_name")
        quotes = request.POST.get("quotes")
        user = "request.user"

        new_quote = Quotes(book_name=book_name, quote=quotes, user=user, username = user.username)
        new_quote.save()    

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Quotes.objects.create(
            user = request.user,
            book_name = data["book_name"],
            quotes = data["quotes"],
            username = request.user.username,
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

quote/templates/add_quote.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Add Quote</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{% endblock meta %}
{% block content %}
    {% include "header.html" %}
    <!-- 536d82, 152040, ffc201, f1e7c6, ffffff -->
    <!-- 27374d, 526d82, 9db2bf, dde6ed -->
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Agbalumo&family=DM+Sans:opsz,wght@9..40,500&display=swap');        body{
            background-color: #152040;
            display: flex; /* Menambahkan display flex untuk mengatur tata letak isi kontainer */
            flex-direction: column; /* Mengatur konten vertikal (sebuah kolom) */
            justify-content: center; /* Mengatur konten secara vertikal tengah */
            align-items: center;
            height: 120vh;
            overflow: hidden;
        }

        .container-fluid{
            flex-direction: column;
            display: flex; /* Menambahkan display flex untuk mengatur tata letak isi kontainer */
            flex-direction: column; /* Mengatur konten vertikal (sebuah kolom) */
            justify-content: center; /* Mengatur konten secara vertikal tengah */
            align-items: center;
            background-color: #f1e7c6;
            width: 600px;
            height: 600px;
            border: 5px solid black;
            border-radius: 30px;
            font-family: 'Agbalumo', sans-serif;
        }

        .button:hover{
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }
    </style>

    <div class="container-fluid d-flex justify-content-center align-items-center">
        <h1 style="font-family: 'Agbalumo', sans-serif;">Add Your Quote</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    <th><label for="{{ form.book_name.id_for_label }}">Book Title:</label></th>
                    <td style="font-family: 'DM Sans', sans-serif;">{{ form.book_name }}</td>
                </tr>
                <tr>
                    <th><label for="{{ form.quote.id_for_label }}">Quote:</label></th>
                    <td style="font-family: 'DM Sans', sans-serif;">{{ form.quotes }}</td>
                </tr>
            </table>
            <div class="container d-flex justify-content-end">
                <a class="button" href="{% url 'quote:quotes_page' %}"
                style="background-color: #f1e7c6; border: 2px solid #f1e7c6; border-radius: 30px; color: black;
                margin-right: 10px; width: 90px; text-align: center;">Back</a>
                <input class="button" type="submit" value="Add New Quote" 
                style="background-color: #f1e7c6; border: 2px solid #f1e7c6; border-radius: 30px;">
            </div>
        </form>
    </div>
    
    {% include "footer.html" %}

{% endblock %}

quote/templates/edit_quote.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Edit Quote</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{% endblock meta %}

{% block content %}

<h1>Edit Your Quote</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td>
                <input type="submit" value="Edit Quote"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

quote/templates/quotes.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Quotes</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{% endblock meta %}

{% block content %}
{% include "header.html" %}
<!-- 536d82, 152040, ffc201, f1e7c6, ffffff -->
<!-- 27374d, 526d82, 9db2bf, dde6ed -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Agbalumo&family=DM+Sans:opsz,wght@9..40,500&display=swap');
        body{
            background-color: #152040;
        }

        .container-fluid{
            background-color: #f1e7c6;
            margin: 100px 50px 30px 50px;
            padding: 20px;
            width: auto;
            height: auto;
            border-radius: 30px;
            align-items: center;
            justify-content: center;
            font-family: 'Agbalumo', sans-serif;        
        }
        
        .row {
            margin: 10px;
        }

        .col-content {
            border: 2px solid #152040;
            border-radius: 30px;
            width: 500px;
            height: 350px;
        }

        .custom-distance{
            margin: 10px 20px 10px 19px;
            padding: 20px;
        }

        .divider {
            border: 2px solid black; 
            margin: 10px ;
        }

        .button-set{
            background-color: #f1e7c6;
            border:0px #f1e7c6;
            font-size: 18px; /* Ubah ukuran font */
            padding: 10px 20px; /* Ubah padding tombol */
            border-radius: 10px; /* Ubah radius sudut tombol */
        }

        .button-set:hover{
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

    </style>

    <div class="container-fluid">
        <div class="row row-cols-3 g-5 align-items-center">
            <div class="col-title d-flex justify-content-left align-items-center">
                <a href="{% url 'quote:add_quote' %}">
                    <button class="button-set">add your quote here!</button>
                </a>
            </div>
            <div class="col-title d-flex justify-content-center align-items-center">
                <h1 style="font-family: 'Agbalumo', sans-serif; font-size:32px;">Your Daily Dose of Quotes</h1>
            </div>
            <div class="col-title d-flex justify-content-end align-items-center">
                <form method="get">
                    <label for="sort_order" style="color: #000000; font-size: 18px;">Ordered based on:</label>
                    <select name="sort_order" id="sort_order" class="dropdown-option" onchange="this.form.submit()">
                        <option value="recent" {% if sort_order == 'recent' %}selected{% endif %}>Recent Qoutes</option>
                        <option value="oldest" {% if sort_order == 'oldest' %}selected{% endif %}>Oldest Quotes</option>
                    </select>
                </form>
            </div>
        </div>
        <div class="row row-cols-3 g-5 align-items-center">
            {% for quote in quotes %}
                <div class="col-content custom-distance" style="font-family: 'Agbalumo', sans-serif;">
                    <h4 style="font-family: 'DM Sans', sans-serif;"><b>@{{quote.user}}</b></h4>
                    <!-- <a href="{% url 'quote:delete_quote' quote.pk %}"><button>Delete</button></a> -->
                    <hr class="divider">
                    <h5 style="font-family: 'DM Sans', sans-serif;"><i>"{{quote.quotes}}"</i></h5>
                    <p style="text-align: right; font-family: 'DM Sans', sans-serif;">-<i><b>{{quote.book_name}}</b></i></p>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include "footer.html" %}

    <script>
        window.onload = function () {
            document.getElementById('sort-order').addEventListener('change', function () {
                const selectedOption = this.value;
                const colQuotes = document.querySelectorAll('.col-content');
                const container = document.querySelector('.container-fluid');

                if (selectedOption === 'recent') {
                    // Mengurutkan ulasan dari yang paling baru
                    const sortedQuotes = Array.from(colQuotes).sort((a, b) => {
                        const dateA = new Date(a.querySelector('.col-content p').textContent);
                        const dateB = new Date(b.querySelector('.col-content p').textContent);
                        return dateB - dateA;
                    });

                    // Mengosongkan container dan menambahkan ulasan yang sudah diurutkan
                    container.innerHTML = '';
                    sortedQuotes.forEach((box) => {
                        container.appendChild(box);
                    });
                } else if (selectedOption === 'oldest') {
                    // Mengurutkan ulasan dari yang paling lama
                    const sortedQuotes = Array.from(colQuotes).sort((a, b) => {
                        const dateA = new Date(a.querySelector('.col-content p').textContent);
                        const dateB = new Date(b.querySelector('.col-content p').textContent);
                        return dateA - dateB;
                    });

                    // Mengosongkan container dan menambahkan ulasan yang sudah diurutkan
                    container.innerHTML = '';
                    sortedQuotes.forEach((box) => {
                        container.appendChild(box);
                    });
                }
            });
        };
    </script>

{% endblock content %}