book/urls.py
from django import views
from django.urls import path, include
from book.views import get_books_by_json, get_books_by_xml, register, login_user, logout_user, show_main, search, get_product_json

app_name = 'book'

urlpatterns = [
    path('json/', get_books_by_json, name='get_book_by_jsons'),
    path('xml/', get_books_by_xml, name='get_by_xml'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='searchbar'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('review/', include("review.urls")),
]

mutualibri/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("book.urls")),
    path('', include("lend.urls")),
    path('review/', include("review.urls")),
    path('quote/', include("quote.urls")),
    path('auth/', include('authentication.urls')),
]

book/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Book(models.Model):
    number = models.BigIntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    voters = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    currency = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    publisher = models.TextField(null=True, blank=True)
    page_count = models.BigIntegerField(null=True, blank=True)
    generes = models.TextField(null=True, blank=True)
    ISBN = models.BigIntegerField(null=True, blank=True)
    language = models.TextField(null=True, blank=True)
    published_date = models.TextField(null=True, blank=True)
    image = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

search/models.py
from django.db import models

# Create your models here.

book/views.py
from collections import UserDict
import json
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse 
from django.core import serializers
from book. models import Book
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from book.models import User



# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, "index.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('book:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('lend:show_catalog')
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('book:login')

def get_books_by_json (request):
    data = Book.objects.all ()
    return HttpResponse (serializers.serialize("json", data), content_type="application/json")

def get_books_by_xml(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def search(request):
    if request.method == "POST":
        searched = request.POST.get('searched')
        books = Book.objects.filter(title__contains=searched)
        return render(request, 'search.html', {'searched': searched, 'books': books})
    else:
        return render(request, 'search.html', {})

def get_product_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

search/views.py
from django.shortcuts import render

# Create your views here.

book/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

book/templates/footer.html
{% block meta %}
<style>
    .footer-07 {
        background: #152040;
      }
      footer {
        padding: 4em 0;
      }
      article, aside, figcaption, figure, footer, header, hgroup, main, nav, section {
        display: block;
      }
      *, ::before, ::after {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
      }
      body {
        font-family: "Poppins", Arial, sans-serif;
        font-size: 15px;
        line-height: 1.8;
        font-weight: normal;
      }
      @media (min-width: 1200px) {
        .container {
          max-width: 1140px;
        }
      }
      .container {
        width: 100%;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
      }
      .text-center {
        text-align: center !important;
      }
      @media (min-width: 768px) {
        .col-md-12 {
          -webkit-box-flex: 0;
          -ms-flex: 0 0 100%;
          flex: 0 0 100%;
          max-width: 100%;
        }
      }
      .footer-07 .footer-heading {
        font-size: 30px;
        color: #fff;
        font-weight: 700;
        margin-bottom: 30px;
      }
      h1, h2, h3, h4, h5, .h1, .h2, .h3, .h4, .h5 {
        line-height: 1.5;
        font-weight: 400;
        font-family: "Poppins", Arial, sans-serif;
      }
      .footer-07 .footer-heading .logo {
        color: #fff;
      }
      .footer-07 a {
        color: #a3de83;
      }
      a {
        -webkit-transition: .3s all ease;
        -o-transition: .3s all ease;
        transition: .3s all ease;
      }
      a {
        color: #007bff;
        text-decoration: none;
        background-color: transparent;
      }
      .footer-07 .menu {
        margin-bottom: 30px;
      }
      .footer-07 p {
        color: rgba(255, 255, 255, 0.3);
      }
      p {
        margin-top: 0;
        margin-bottom: 1rem;
      }
      .footer-07 .menu a {
        color: rgba(255, 255, 255, 0.6);
        margin: 0 10px;
        text-transform: uppercase;
        letter-spacing: 1px;
      }

      .p-0 {
        padding: 0 !important;
      }
      ol, ul, dl {
        margin-top: 0;
        margin-bottom: 1rem;
      }
</style>
{% endblock meta %}

{% block content %}
<footer class="footer-07">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <h2 class="footer-heading"><a href="#" class="logo">Mutualibri</a></h2>
                <p class="menu">
                    <a href="#">Home</a>
                    <a href="#">Catalog</a>
                    <a href="#">Review</a>
                    <a href="#">Quotes</a>
                    <a href="#">About Us</a>
                </p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12 text-center">
                <p class="copyright">
                    Copyright ©<script>document.write(new Date().getFullYear());</script> All rights reserved | This web is made with <i class="ion-ios-heart" aria-hidden="true" style:readonly></i> by <a href="">Mutualibri</a>                
                </p>
            </div>
        </div>
    </div>
</footer>
{% endblock content %}

book/templates/login.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background: #23242a;
    color: #8f8f8f;
    background-image: linear-gradient(#ECBD00, #EBD798);
  }

  .box {
    position: relative;
    width: 420px;
    height: 450px;
    background: #152040;
    border-radius: 20px;
    overflow: hidden;
  }

  .borderLine {
    position: absolute;
    top: 0;
    inset: 0;
  }

  .box form {
    position: absolute;
    inset: 4px;
    background: #ffffff;
    padding: 50px 40px;
    border-radius: 18px;
    z-index: 2;
    display: flex;
    flex-direction: column;
  }

  .box form h2 {
    color: #27374D;
    font-weight: 700;
    text-align: center;
    letter-spacing: 0.1em;
  }

  .box form .inputBox {
    position: relative;
    width: 320px;
    margin-top: 35px;
  }

  .box form .inputBox .form-control {
      color:white;
  }

  .box form .inputBox input {
    position: relative;
    width: 100%;
    padding: 20px 10px 10px;
    background: transparent;
    outline: none;
    border: none;
    box-shadow: none;
    color: #27374D;
    font-size: 1em;
    letter-spacing: 0.05em;
    transition: 0.5s;
    z-index: 10;
  }

  .box form .inputBox span {
    position: absolute;
    left: 0;
    padding: 20px 0px 10px;
    pointer-events: none;
    color: #27374D;
    font-size: 1em;
    letter-spacing: 0.05em;
    transition: 0.5s;
  }

  .box form .inputBox input:valid ~ span,
  .box form .inputBox input:focus ~ span {
      color: white;
      font-size: 0.75em;
      transform: translateY(-34px);
  }

  .box form .inputBox i {
      position: absolute;
      left: 0;
      bottom: 0;
      width: 100%;
      height: 2px;
      background: #27374D;
      border-radius: 7px;
      overflow: hidden;
      transition: 0.5s;
      pointer-events: none;
  }

  .box form .inputBox input:valid ~ i,
  .box form .inputBox input:focus ~ i {
      height: 44px;
  }

  .box form .links {
      display: flex;
      justify-content: space-between;
      margin-top: 15px;
  }

  .box form .wordle {
      margin-top: 10px;
      width: 100%;
      text-align:center;
  }
  .box form .links input {
      color:white;
  }

  .box form .links a {
    margin: 15px 12px 20px 0;
    font-size: 0.75em;
    color: white;
    text-decoration: none;
  }

  .box form .links a:hover,
  .box form .links a:nth-child(2) {
    color: white;
  }

  .box form input[type="submit"] {
    position: center;
    border: none;
    outline: none;
    padding: 9px 25px;
    background: #152040;
    cursor: pointer;
    font-size: 0.9em;
    border-radius: 7px;
    font-weight: 600;
    width: 100%;
    margin-top: 35px;
    transition: 0.6s;
  }

  .box form input[type="submit"]:hover {
    background-color: #04364A;
  }

  .box form input[type="submit"]:active {
    opacity: 0.8;
  }

  .box form button {
      border: none;
      outline: none;
      padding: 9px 25px;
      background: #152040;
      cursor: pointer;
      font-size: 0.9em;
      border-radius: 7px;
      font-weight: 600;
      width: 100%;
      margin-top: 10px;
      transition: 0.6s;
      color:white;
  }

  .box form button:hover {
    background-color: #04364A;
  }
</style>
{% endblock meta %}

{% block content %}

<div class="box">
  <span class="borderLine"></span>
  <form method="POST" action="">
    {% csrf_token %}  
    <h2>Log In</h2>
    <div class="inputBox">
      <span>Username</span>
      <input type="text" required="required" name="username" class="form-control">
      <i></i>
    </div>
    <div class="inputBox">
      <span>Password</span>
      <input type="password" required="required" name="password"  class="form-control">
      <i></i>
    </div>
    <div class="links">
        <input class="btn btn-primary w-100 py-2" type="submit" value="Login">
    </div>
    <div class="wordle">
        Don't have an account? <a href="{% url 'book:register' %}" style="text-decoration: none;">Register Now!</a>
    </div>
    <div>
    </div>
  </form>
  {% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
  {% endif %}
</div>

{% endblock content %}

book/templates/navbar.html
{% block meta %}
<style>
    .p-3 {
        padding: 1rem !important;
      }
</style>
{% endblock meta %}

{% block content %}
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>
{% endblock content %}

book/templates/register.html
{% extends "base.html" %} 

{% block meta %}
{% load static %} 
<title>Register</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
      margin: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background: #23242a;
      color: #8f8f8f;
      background-image: linear-gradient(#ECBD00, #EBD798);
    }

  .box {
    position: relative;
    width: 1000px;
    height: 500px;
    background: #152040;
    border-radius: 20px;
    overflow: hidden;
  }

  .borderLine {
    position: absolute;
    top: 0;
    inset: 0;
  }

  .box form {
    position: absolute;
    inset: 4px;
    background: #FFFF;
    padding: 50px 40px;
    border-radius: 18px;
    z-index: 2;
    display: flex;
    flex-direction: column;
  }

  .box form h2 {
    color: #27374D;
    font-weight: 500;
    text-align: center;
    letter-spacing: 0.1em;
    margin-bottom:35px;
  }

  .box form .inputBox {
    position: relative;
    width: 300px;
    margin-top: 35px;
  }

  .box form .inputBox input {
    position: relative;
    width: 100%;
    padding: 20px 10px 10px;
    background: transparent;
    outline: none;
    border: none;
    box-shadow: none;
    color: #27374D;
    font-size: 1em;
    letter-spacing: 0.05em;
    transition: 0.5s;
    z-index: 10;
    color:white;
  }

  .box form .inputBox span {
    position: absolute;
    left: 0;
    padding: 20px 0px 10px;
    pointer-events: none;
    color: #27374D;
    font-size: 1em;
    letter-spacing: 0.05em;
    transition: 0.5s;
  }

  .box form .inputBox input:valid ~ span,
  .box form .inputBox input:focus ~ span {
      color: white;
      font-size: 0.75em;
      transform: translateY(-34px);
  }

  .box form .inputBox i {
      position: absolute;
      left: 0;
      bottom: 0;
      width: 100%;
      height: 2px;
      background: #27374D;
      border-radius: 7px;
      overflow: hidden;
      transition: 0.5s;
      pointer-events: none;
  }

  .box .borderLine form .form-floating {
      color: black;
  }
  .box form .inputBox input:valid ~ i,
  .box form .inputBox input:focus ~ i {
      height: 44px;
  }

  .box form .links {
      display: flex;
      justify-content: space-between;
      margin-top: 15px;
  }
  .box form .links input {
      color:white;
  }

  .box form .links a {
    margin: 15px 12px 20px 0;
    font-size: 0.75em;
    color: white;
    text-decoration: none;
  }

  .box form .links a:hover,
  .box form .links a:nth-child(2) {
    color: white;
  }

  .box form input[type="submit"] {
    border: none;
    outline: none;
    padding: 9px 25px;
    background: #152040;
    cursor: pointer;
    font-size: 0.9em;
    border-radius: 7px;
    font-weight: 600;
    width: 100px;
    margin-top: 10px;
    transition: 0.6s;
  }

  .box form input[type="submit"]:hover {
    background-color: #04364A;
  }

  .box form input[type="submit"]:active {
    opacity: 0.8;
  }
  table.form-table td {
      padding-bottom:20px;
      color: black;
  }

  label {
      display: inline-block;
      color: black;
    }
</style>

{% endblock meta %}

{% block content %}

<div class="box">
  <span class="borderLine"></span>
  <form method="POST" action="">
    {% csrf_token %}  
    <h2>Register</h2>
    <div class="form-floating form-table">
        <table class="form-table">  
            {{ form.as_table }}  
            <tr>  
                <td>
                </td>
                <td><input style="color:white;" class="btn btn-primary w-100 py-2" type="submit" name="submit" value="Register "/></td>  
            </tr>  
        </table>  
    </div>
  </form>
  {% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
  {% endif %}
</div>

{% endblock content %}

book/templates/search.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Search</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<style>
    /* Set the background color for the entire HTML */
    body {
        background-color: #152040; /* Update background color to #152040 */
    }

    /* Center the search results and give them some spacing */
    .container {
        text-align: center;
        padding: 20px;
    }

    /* Style the search results title */
    .text-center h1 {
        font-size: 24px;
        margin: 20px 0;
    }

    /* Style the card */
    .card {
        border: none;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s;
        background-color: #27374D; /* Background color of the card (#27374D) */
        color: black; /* Text color inside the card (white) */
        height: 100%;
    }

    .card:hover {
        transform: translateY(-5px);
    }

    /* Style the card title */
    .card-title-box {
        background-color: #526D82; /* Background color for the title box (#526D82) */
        padding: 10px;
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
    }

    .card-title {
        font-size: 18px;
        margin: 0;
        color: #fff; /* Text color for the title (white) */
    }

    /* Style the card description */
    .card-text {
        font-size: 16px;

    }
    .row {
        display: flex;
        justify-content: center;
        background-color: #152040;
    }

    .col-lg-3 {
            flex: 0 0 25%}
</style>
{% endblock meta %}
{% block content %}
{% include 'header.html' %}

<div id="product_table">
    <!-- {% if searched %}
    <h1 class="text-light text-center">Your Search Results for "{{ searched }}"</h1>
    <div class="row">
        {% for book in books %}
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="card-title-box">
                        <h5 class="card-title">{{ book.title }}</h5>
                    </div>
                    <img class="card-img-top" src="{{ book.image.url }}" alt="{{ book.title }}">
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:2 %}
        </div><div class="row">
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <h1 class="text-light text-center">No Input!</h1>
    {% endif %}
</div>-->
<script>
    // Function to filter books
    function filterBooks() {
        var input, filter, productTable, books, book, title, txtValue;
        input = document.getElementById('search');
        filter = input.value.toLowerCase();
        productTable = document.getElementById('product_table');
        books = productTable.getElementsByClassName('col-lg-3');

        for (var i = 0; i < books.length; i++) {
            book = books[i];
            title = book.getElementsByClassName('card-title')[0];
            txtValue = title.textContent || title.innerText;

            if (txtValue.toLowerCase().indexOf(filter) > -1) {
                book.style.display = '';
            } else {
                book.style.display = 'none';
            }
        }
    }

    // Add an event listener to trigger the filtering
    document.getElementById('search').addEventListener('input', filterBooks);

    // Fetch and display products initially
    async function getAndDisplayProducts() {
        const productTable = document.getElementById('product_table');
        try {
            const response = await fetch("{% url 'book:get_product_json' %}");
            const products = await response.json();

            let htmlString = '';

            for (let i = 0; i < products.length; i++) {
                const item = products[i];

                if (i % 4 === 0) {
                    if (i > 0) {
                        htmlString += '</div>';
                    }
                    htmlString += '<div class="row">';
                }

                htmlString += `
                    <div class="col-lg-3 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="card-title-box">
                                    <h5 class="card-title">${item.fields.title}</h5>
                                </div>
                                <img class="card-img-top" src="${item.fields.image}" alt="${item.fields.title}">
                            </div>
                        </div>
                    </div>
                `;

                if (i === products.length - 1) {
                    htmlString += '</div>';
                }
            }

            productTable.innerHTML = htmlString;
        } catch (error) {
            console.error('Error fetching and displaying products:', error);
        }
    }

    getAndDisplayProducts();
</script>
{% endblock %}