book/urls.py
from django import views
from django.urls import path, include
from book.views import get_books_by_json, get_books_by_xml, register, login_user, logout_user, show_main, search, get_product_json

app_name = 'book'

urlpatterns = [
    path('json/', get_books_by_json, name='get_book_by_jsons'),
    path('xml/', get_books_by_xml, name='get_by_xml'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='searchbar'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('review/', include("review.urls")),
]

lend/urls.py
from django.urls import path
from lend.views import create_lend_flutter, show_catalog, get_catalog_json, get_book, get_book_json, preview_lend, show_json, show_sorted, get_book_new, delete_lend_flutter

app_name = 'lend'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
    path('get-catalog/', get_catalog_json, name='get_catalog_json'),
    path('get-one-book/<int:id>/', get_book, name='get_book'),
    path('get-book-json/<int:id>/', get_book_json, name="get_book_json"),
    path('get-one-book/<int:id>/preview-lend/', preview_lend, name="preview_lend"),
    path('json/', show_json, name='show_json'),
    path('filter/', show_sorted, name='filter'),
    path('get-book-new/<int:id>/', get_book_new, name='get_book_new'),
    path('create-lend-flutter/', create_lend_flutter, name="create_lend_flutter"),
    path('delete-lend-flutter/', delete_lend_flutter, name="delete_lend_flutter"),
]

mutualibri/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("book.urls")),
    path('', include("lend.urls")),
    path('review/', include("review.urls")),
    path('quote/', include("quote.urls")),
    path('auth/', include('authentication.urls')),
]

book/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Book(models.Model):
    number = models.BigIntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    voters = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    currency = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    publisher = models.TextField(null=True, blank=True)
    page_count = models.BigIntegerField(null=True, blank=True)
    generes = models.TextField(null=True, blank=True)
    ISBN = models.BigIntegerField(null=True, blank=True)
    language = models.TextField(null=True, blank=True)
    published_date = models.TextField(null=True, blank=True)
    image = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

lend/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

# Create your models here.
class Lend(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    number = models.IntegerField()

lend/forms.py
from django import forms
from lend.models import Lend
from django.utils import timezone

class LendForm(forms.ModelForm):
    class Meta:
        model = Lend
        fields = []

    def __init__(self, user, book_id, *args, **kwargs):
        super(LendForm, self).__init__(*args, **kwargs)
        current_date = timezone.now()
        future_date = current_date + timezone.timedelta(days=7)
        self.initial['start_date'] = current_date
        self.initial['end_date'] = future_date
        self.user = user
        self.book_id = book_id
        # Set number to the book_id
        self.initial['number'] = book_id

    def save(self, commit=True):
        lend = super(LendForm, self).save(commit=False)
        lend.user = self.user
        lend.book_id = self.book_id
        lend.start_date = self.initial['start_date']
        lend.end_date = self.initial['end_date']
        lend.number = self.initial['number']  # Isi number dari initial
        if commit:
            lend.save()
        return lend


class BookFilterForm(forms.Form):
    title = forms.CharField(required=False)
    author = forms.CharField(required=False)

book/views.py
from collections import UserDict
import json
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse 
from django.core import serializers
from book. models import Book
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from book.models import User



# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, "index.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('book:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('lend:show_catalog')
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('book:login')

def get_books_by_json (request):
    data = Book.objects.all ()
    return HttpResponse (serializers.serialize("json", data), content_type="application/json")

def get_books_by_xml(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def search(request):
    if request.method == "POST":
        searched = request.POST.get('searched')
        books = Book.objects.filter(title__contains=searched)
        return render(request, 'search.html', {'searched': searched, 'books': books})
    else:
        return render(request, 'search.html', {})

def get_product_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

lend/views.py
import datetime
import json

# Create your views here.
from django.shortcuts import render
from lend.models import Lend
from book.models import Book
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from datetime import date, timedelta
from .models import User
from lend.forms import LendForm, BookFilterForm
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse 
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='book/login')
def show_catalog(request):  
    books = Book.objects.all()
    context = {
        'books':books,
        'name':request.user.username,
        'images':['https://www.booktopia.com.au/covers/big/9781612626796/0000/attack-on-titan-vol-13.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0N5d_ivUHjwRT-biqpXzfCESXuS4VmTc9xcnghMRtUr7c4mbck4AjPDRdhDHGouwHcjI&usqp=CAU', ],
    }

    return render(request, "catalog.html", context)

def show_sorted(request): 
    form = BookFilterForm(request.GET)  # Gunakan request.GET untuk mendapatkan parameter filter dari URL
    books = Book.objects.all()

    if form.is_valid():
        title = form.cleaned_data.get('title')
        author = form.cleaned_data.get('author')

        if title:
            books = books.filter(title__icontains=title)

        if author:
            books = books.filter(author__icontains=author)

    context = {
        'books': books,
        'name': request.user.username,
        'images': ['https://www.booktopia.com.au/covers/big/9781612626796/0000/attack-on-titan-vol-13.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0N5d_ivUHjwRT-biqpXzfCESXuS4VmTc9xcnghMRtUr7c4mbck4AjPDRdhDHGouwHcjI&usqp=CAU', ],
        'form': form,  # Tambahkan form ke dalam konteks
    }

    return render(request, "filter.html", context)

def get_catalog_json(request):
    product_item = Book.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def get_book_new(request, id):
    url = reverse('get_book', args=[id])
    return HttpResponseRedirect(url)

def get_book(request, id):
    books = Book.objects.filter(pk=id)
    user= request.user
    context = {
        'books':books,
        'id':id,
        'user':user,
    }
    return render(request, "book_view.html", context)

def get_book_json(request, id):
    product_item = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('json', product_item))

def preview_lend(request, id):
    book = Book.objects.get(pk=id)
    form = LendForm(request.user, book.id)
    
    if request.method == 'POST':
        form = LendForm(request.user, book.id, request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('lend:show_catalog'))
            # Redirect atau lakukan apa yang diperlukan setelah pengajuan pinjaman
    return render(request, 'preview_lend.html', {'form': form, 'book': book, 'id':id})
    
def show_json(request):
    lend = Lend.objects.filter(user=request.user)
    data = serializers.serialize('json', lend)
    return HttpResponse(data, content_type="application/json")

@csrf_exempt
def create_lend_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        book = Book.objects.get(number=int(data["book"]))
        start = data["startDate"][:10]
        end = data["endDate"][:10]

        new_product = Lend.objects.create(
            user = request.user,
            book = book,
            start_date = datetime.datetime.strptime(start, "%Y-%m-%d"),
            end_date = datetime.datetime.strptime(end, "%Y-%m-%d"),
            number = int(data["number"]),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
        
@csrf_exempt
def delete_lend_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        try:
            book = Lend.objects.get(pk=int(data['pk']))
            if request.user == book.user:
                book.delete()
            return JsonResponse({'status': 'success'})
        except Book.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Book not found'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

lend/templates/filter.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Filter</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock meta %}

{% block content %}
<form method="get" action="">
    {{ form.title.label_tag }} {{ form.title }}
    {{ form.author.label_tag }} {{ form.author }}
    <button type="submit">Filter</button>
</form>
<ul>
    {% for book in books %}
        <li style="color:black;">{{ book.title }} by {{ book.author }}</li>
    {% endfor %}
</ul>

{% endblock content %}

lend/templates/preview_lend.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<title>Lend Book</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<style>
    * {
        line-height:21px;
      }
    @use postcss-preset-env {
        stage: 0;
    }
    html {
        background-color:#152040;
    }
    :root {
        --color-background: #152040;
        --color-primary: #fc8080;
        --font-size-h1: 1.25rem;
        --font-size-h2: 1rem;
    }
       
    * {
        box-sizing: inherit;
    }
      
    html {
        box-sizing: border-box;
    }
      
    body {

        display: grid;
        line-height: 1.5;
        margin: 0;
        min-block-size: 100vh;
        place-items: center;
    }
      
    address {
        font-style: normal;
    }
    
    fieldset {
        border: 0;
        margin: 0;
        padding: 0;
    }
      
    h1 {
        font-size: 30px;
        line-height: 1.2;
        margin-block: 0 0.5em;
    }
    
    h2 {
        font-size: var(--font-size-h2);
        line-height: 1.2;
        margin-block: 0 0.5em;
    }
      
    legend {
        font-weight: 600;
        margin-block-end: 0.5em;
        padding: 0;
    }
    
    input {
        border: 0;
        color: inherit;
        font: inherit;
    }
      
    input[type="radio"] {
        accent-color: var(--color-primary);
    }
    
    table {
        border-collapse: collapse;
        inline-size: 100%;
    }
    
    tbody {
        color: #b4b4b4;
    }
    
    td {
        padding-block: 0.125em;
    }
      
    tfoot {
        border-top: 1px solid #b4b4b4;
        font-weight: 600;
    }
    
    .align {
        display: grid;
        place-items: center;
    }
    
    body {
        margin: 0;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        background-color: #152040;
        -webkit-text-size-adjust: 100%;
        -webkit-tap-highlight-color: transparent;
    }

    .button {
        align-items: center;
        background-color: #FFC200;
        border-radius: 999em;
        color: black;
        display: flex;
        gap: 0.5em;
        justify-content: center;
        padding-block: 0.75em;
        padding-inline: 1em;
        transition: 0.3s;
    }
      
    .button:hover {
        background-color: #e96363;
    }
    
    .button--full {
        inline-size: 100%;
    }
      
    .card {
        border-radius: 1em;
        background-color:#FFC200;
        color: black;
        padding: 1em;
        margin-bottom:30px;
        margin-top:10px;
    }
      
    .form {
        display: grid;
        gap: 2em;
    }
    
    .form__radios {
        display: grid;
        gap: 1em;
        margin-bottom:10px;
    }
    
    .form__radio {
        align-items: center;
        background-color: #fefdfe;
        border-radius: 1em;
        box-shadow: 0 0 1em rgba(0, 0, 0, 0.0625);
        display: flex;
        padding: 1em;
    }
      
    .form__radio label {
        align-items: center;
        display: flex;
        flex: 1;
        gap: 1em;
    }
    
    .header {
        display: flex;
        justify-content: center;
        padding-block: 0.5em;
        padding-inline: 1em;
    }
    
    .icon {
        block-size: 1em;
        display: inline-block;
        fill: currentColor;
        inline-size: 1em;
        vertical-align: middle;
    }
      
    .iphone {
        background-color: #fbf6f7;
        background-image: linear-gradient(to bottom, #fbf6f7, #fff);
        border-radius: 2em;
        box-shadow: 0 0 1em rgba(0, 0, 0, 0.0625);
        inline-size: 375px;
        overflow: auto;
        padding: 2em;
    }
</style>
{% endblock meta %}

{% include "header.html" %}
{% block content %}
<div class="iphone" id="product_table" style="margin-top:100px;">
</div>

<script>

  // Get the current date
  const currentDate = new Date();

  // Calculate the end date (7 days later)
  const endDate = new Date(currentDate);
  endDate.setDate(currentDate.getDate() + 7);

  // Format the dates as yyyy-mm-dd for input fields
  const startDateValue = currentDate.toISOString().slice(0, 10);
  const endDateValue = endDate.toISOString().slice(0, 10);

  async function getProducts() {
      return fetch("{% url 'lend:get_catalog_json' %}").then((res) => res.json())
  }

  async function refreshProducts() {
      document.getElementById("product_table").innerHTML = ""
      var pk = "{{ id }}"
      const products = await getProducts()
      let htmlString = ``
      products.forEach((book) => {
          if (pk == book.pk) {
              htmlString += ` 
                  <h1 class="header"><b>Lend Book</b></h1>
                  <div>
                    <legend>Title of the Book</legend>
                    <div class="card">
                      <p>${book.fields.title}</p>
                    </div>
                  </div>
          
                  <fieldset>
                    <legend>Detail Lend</legend>
                    <div class="form__radios">
                      <div class="form__radio">
                        <label for="start_date" readonly>Start Date: ${startDateValue}</label>
                      </div>
                      <div class="form__radio">
                        <label for="end_date" readonly>End Date: ${endDateValue}</label>
                      </div>
                    </div>
                  </fieldset>
                  <form method="post">
                    {% csrf_token %}
            
                    <div>
                        {{ form.user.label_tag }}
                        
                    </div>
            
                    <div>
                        {{ form.book.label_tag }}
                        {{ form.book }}
                    </div>
            
                    <!-- These fields are hidden -->
                    {{ form.start_date }}
                    {{ form.end_date }}
                    {{ form.number }}
                    <div>
                        <input class="button button--ful" type="submit" value="Lend Now!">
                    </div>
                </form>`;
          };
      })

        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts() 

    // Set the input field values
    document.getElementById("start_date").value = startDateValue;
    document.getElementById("end_date").value = endDateValue;

    var modal = document.getElementById('myModal');
    var btn = document.getElementById("myBtn");
    var span = document.getElementsByClassName("close")[0];

    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }
</script>
{% include "footer.html" %}
{% endblock content %}

lend/templates/sort_catalog.html
{% extends 'base.html' %}
{% block meta %}
<style>
    /* Set the background color for the entire HTML */
    body {
        background-color: #152040; /* Update background color to #152040 */
    }

    /* Center the search results and give them some spacing */
    .container {
        text-align: center;
        padding: 20px;
    }

    /* Style the search results title */
    .text-center h1 {
        font-size: 24px;
        margin: 20px 0;
    }

    /* Style the card */
    .card {
        border: none;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s;
        background-color: #27374D; /* Background color of the card (#27374D) */
        color: black; /* Text color inside the card (white) */
        height: 100%;
    }

    .card:hover {
        transform: translateY(-5px);
    }

    /* Style the card title */
    .card-title-box {
        background-color: #526D82; /* Background color for the title box (#526D82) */
        padding: 10px;
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
    }

    .card-title {
        font-size: 18px;
        margin: 0;
        color: #fff; /* Text color for the title (white) */
    }

    /* Style the card description */
    .card-text {
        font-size: 16px;

    }
    .row {
        display: flex;
        justify-content: center;
    }

    .col-lg-3 {
            flex: 0 0 25%}
</style>
{% endblock meta %}
{% block content %}
{% include 'header.html' %}

<div id="product_table">
    <!-- {% if searched %}
    <h1 class="text-light text-center">Your Search Results for "{{ searched }}"</h1>
    <div class="row">
        {% for book in books %}
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="card-title-box">
                        <h5 class="card-title">{{ book.title }}</h5>
                    </div>
                    <img class="card-img-top" src="{{ book.image.url }}" alt="{{ book.title }}">
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:2 %}
        </div><div class="row">
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <h1 class="text-light text-center">No Input!</h1>
    {% endif %}
</div>-->
<script>
    // Function to filter books
    function filterBooks() {
        var input, filter, productTable, books, book, title, txtValue;
        input = document.getElementById('search');
        filter = input.value.toLowerCase();
        productTable = document.getElementById('product_table');
        books = productTable.getElementsByClassName('col-lg-3');

        for (var i = 0; i < books.length; i++) {
            book = books[i];
            title = book.getElementsByClassName('card-title')[0];
            txtValue = title.textContent || title.innerText;

            if (txtValue.toLowerCase().indexOf(filter) > -1) {
                book.style.display = '';
            } else {
                book.style.display = 'none';
            }
        }
    }

    // Add an event listener to trigger the filtering
    document.getElementById('search').addEventListener('input', filterBooks);

    // Fetch and display products initially
    async function getAndDisplayProducts() {
        const productTable = document.getElementById('product_table');
        try {
            const response = await fetch("{% url 'book:get_product_json' %}");
            const products = await response.json();

            let htmlString = '';

            for (let i = 0; i < products.length; i++) {
                const item = products[i];

                if (i % 4 === 0) {
                    if (i > 0) {
                        htmlString += '</div>';
                    }
                    htmlString += '<div class="row">';
                }

                htmlString += `
                    <div class="col-lg-3 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="card-title-box">
                                    <h5 class="card-title">${item.fields.title}</h5>
                                </div>
                                <img class="card-img-top" src="${item.fields.image}" alt="${item.fields.title}">
                            </div>
                        </div>
                    </div>
                `;

                if (i === products.length - 1) {
                    htmlString += '</div>';
                }
            }

            productTable.innerHTML = htmlString;
        } catch (error) {
            console.error('Error fetching and displaying products:', error);
        }
    }

    getAndDisplayProducts();
</script>
{% endblock %}

lend/templates/success_create.html
{% block meta %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<style>
    body{
		background:#152040;
	}

	* {
		font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
	}

	h1,h2,h3 {
		font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;

	}
	
	p {
		margin-left:20px;
		margin-right:20px;
	}
	
	.card{
		border:none;
		position:relative;
		overflow:hidden;
		border-radius:8px;
		cursor:pointer;
	}
	
	.card:before{
		content:"";
		position:absolute;
		left:0;
		top:0;
		width:4px;
		height:100%;
		background-color:#FFC200;
		transform:scaleY(1);
		transition:all 0.5s;
		transform-origin: bottom
	}
	
	.card:after{
		content:"";
		position:absolute;
		left:0;
		top:0;
		width:4px;
		height:100%;
		background-color:#AAAAA;
		transform:scaleY(0);
		transition:all 0.5s;
		transform-origin: bottom
	}
	
	.card:hover::after{
		transform:scaleY(1);
	}
	
	
	.fonts{
		font-size:11px;
	}
	
	.social-list{
		display:flex;
		list-style:none;
		justify-content:center;
		padding:0;
	}
	
	.social-list li{
		padding:10px;
		color:#8E24AA;
		font-size:19px;
	}
	
	
	.buttons button:nth-child(1){
		   border:1px solid #8E24AA !important;
		   color:#8E24AA;
		   height:40px;
	}
	
	.buttons button:nth-child(1):hover{
		   border:1px solid #8E24AA !important;
		   color:#fff;
		   height:40px;
		   background-color:#8E24AA;
	}
	
	.buttons button:nth-child(2){
		   border:1px solid #8E24AA !important;
		   background-color:#8E24AA;
		   color:#fff;
			height:40px;
	}
	.back-button {
		background-color: #152040;
		color: white;
		border: none; 
		border-radius: 5px; 
		padding: 10px 20px; 
		cursor: pointer; 
		font-size: 16px; 
		font-weight: bold; 
	}

	.back-button:hover {
		background-color: grey; 
	}
</style>
{% endblock meta %}

{% block content %}
{% include "header.html" %}

<div style="margin-top:150px;">
	<div class="container mt-5">
		
		<div class="row d-flex justify-content-center">
			
			<div class="col-md-7">
				
				<div class="card p-3 py-4">
					
					<div class="text-center mt-3">
						<h1 style="text-align:center;">SUCCESS!</h1>
						<p>"Thank you for borrowing books from our library! We greatly appreciate your interest in our collection. Your enthusiasm for reading and your support of our library are what keep us going. We hope you find the books you've borrowed enjoyable and informative. Please remember to return them on time so that others can also benefit from these resources. If you have any questions or need assistance with anything related to your borrowed books or any other library services, please don't hesitate to reach out to us. Happy reading!" </p>
						<h2 style="text-align:center;">Your Number Book</h2>
						<h3 style="text-align:center;">{{id}}</h3>
						<a href="/lendbook"><button class="back-button">OK</button></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% comment %} 

<div id="modal">
	<article class="modal-container">
		<section class="modal-container-body rtf">
		</section>
		<footer class="modal-container-footer">
			<a href="/lendbook"><button class="back-button">Back</button></a>
		</footer>
	</article>
</div> {% endcomment %}
{% include "footer.html" %}
{% endblock content %}