book/urls.py
from django import views
from django.urls import path, include
from book.views import get_books_by_json, get_books_by_xml, register, login_user, logout_user, show_main, search, get_product_json

app_name = 'book'

urlpatterns = [
    path('json/', get_books_by_json, name='get_book_by_jsons'),
    path('xml/', get_books_by_xml, name='get_by_xml'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='searchbar'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('review/', include("review.urls")),
]

lend/urls.py
from django.urls import path
from lend.views import create_lend_flutter, show_catalog, get_catalog_json, get_book, get_book_json, preview_lend, show_json, show_sorted, get_book_new, delete_lend_flutter

app_name = 'lend'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
    path('get-catalog/', get_catalog_json, name='get_catalog_json'),
    path('get-one-book/<int:id>/', get_book, name='get_book'),
    path('get-book-json/<int:id>/', get_book_json, name="get_book_json"),
    path('get-one-book/<int:id>/preview-lend/', preview_lend, name="preview_lend"),
    path('json/', show_json, name='show_json'),
    path('filter/', show_sorted, name='filter'),
    path('get-book-new/<int:id>/', get_book_new, name='get_book_new'),
    path('create-lend-flutter/', create_lend_flutter, name="create_lend_flutter"),
    path('delete-lend-flutter/', delete_lend_flutter, name="delete_lend_flutter"),
]

mutualibri/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include("book.urls")),
    path('', include("lend.urls")),
    path('review/', include("review.urls")),
    path('quote/', include("quote.urls")),
    path('auth/', include('authentication.urls')),
]

quote/urls.py
from django.urls import path
from quote.views import create_product_flutter, quotes_page, add_quote, edit_quote, delete_quote, show_json, show_json_by_id, add_quote_ajax\
, get_quote

app_name = 'quote'

urlpatterns = [
    path('', quotes_page, name='quotes_page'),
    path('add-quote', add_quote, name='add_quote'),
    path('edit-quote/<int:id>/', edit_quote, name='edit_quote'),
    path('delete-quote/<int:id>/', delete_quote, name='delete_quote'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('get-quote/', get_quote, name='get_quote'),
    path('add-quote-ajax/', add_quote_ajax, name='add_quote_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

review/urls.py
from django.urls import path
from review.views import create_review_flutter, show_main, create_review_ajax, create_review, show_json,show_json_by_id
from . import views

app_name = 'review'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_review', create_review, name='create_review'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('show-main/recent/', views.show_main, {'sort_order': 'recent'}, name='show_main_recent'),  
    path('show-main/oldest/', views.show_main, {'sort_order': 'oldest'}, name='show_main_oldest'),  
    path('create-flutter/', create_review_flutter, name='create_review_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/footer.html
{% extends "base.html" %} {% load static %} 

{% block meta %}
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<style>
    .footer-07 {
        background-color: #152040;
      }
      footer {
        padding: 4em 0;
      }
      article, aside, figcaption, figure, footer, header, hgroup, main, nav, section {
        display: block;
      }
      *, ::before, ::after {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
      }
      body {
        background-color: #152040;
        font-size: 15px;
        line-height: 1.8;
        font-weight: normal;
      }
      @media (min-width: 1200px) {
        #containerid {
          max-width: 1140px;
        }
      }
      #containerid {
        width: 100%;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
      }
      .text-center {
        text-align: center !important;
      }
      @media (min-width: 768px) {
        .col-md-12 {
          -webkit-box-flex: 0;
          -ms-flex: 0 0 100%;
          flex: 0 0 100%;
          max-width: 100%;
        }
      }
      .footer-07 .footer-heading {
        font-size: 30px;
        color: #fff;
        font-weight: 700;
        margin-bottom: 30px;
      }
      h1, h2, h3, h4, h5, .h1, .h2, .h3, .h4, .h5 {
        line-height: 1.5;
        font-weight: 400;
      }
      .footer-07 .footer-heading .logo {
        color: #fff;
      }
      .footer-07 a {
        color: #a3de83;
      }
      a {
        -webkit-transition: .3s all ease;
        -o-transition: .3s all ease;
        transition: .3s all ease;
      }
      a {
        color: #007bff;
        text-decoration: none;
        background-color: transparent;
      }
      .footer-07 .menu {
        margin-bottom: 30px;
      }
      .footer-07 p {
        color: rgba(255, 255, 255, 0.3);
      }
      p {
        margin-top: 0;
        margin-bottom: 1rem;
      }
      .footer-07 .menu a {
        color: rgba(255, 255, 255, 0.6);
        margin: 0 10px;
        text-transform: uppercase;
        letter-spacing: 1px;
      }

      .p-0 {
        padding: 0 !important;
      }
      ol, ul, dl {
        margin-top: 0;
        margin-bottom: 1rem;
      }
</style>
{% endblock meta %}

{% block content %}
<footer class="footer-07">
    <div id="containerid">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <h2 class="footer-heading"><a href="#" class="logo">Mutualibri</a></h2>
                <p class="menu">
                    <a href="{% url "lend:show_catalog" %}">Catalog</a>
                    <a href="{% url "review:show_main" %}">Review</a>
                    <a href="{% url "quote:quotes_page"%}">Quotes</a>
                    <a href="{% url "book:login" %}">Logout</a>
                </p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12 text-center">
                <p class="copyright">
                Copyright ©<script>document.write(new Date().getFullYear());</script> All rights reserved | This web is made with <i class="ion-ios-heart" aria-hidden="true" style:readonly></i> by <a href="">Mutualibri</a>
                </p>
            </div>
        </div>
    </div>
</footer>
{% endblock content %}

templates/header.html
{% extends "base.html" %} 
{% load static %} 

{% block meta %}
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
    <style>
        .p-2 {
            padding: 1rem !important;
            position:fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 9999;
        }

        .text-bg-dark {
            color: #fff !important; /* Teks berwarna putih */
        }

        .navbar-bg-dark {
            background-color: #152040 !important; /* Latar belakang navbar (#27374D) */
        }

        .form-control-dark {
            border-color: #526D82 !important; /* Warna border form input (#526D82) */
            color: black !important; /* Warna teks dalam form input (putih) */
        }

        .btn-outline-light {
            color: #fff !important; /* Warna teks tombol (putih) */
            border-color: #fff !important; /* Warna border tombol (putih) */
        }

        .btn-warning {
            background-color: #526D82 !important; /* Latar belakang tombol Sign-up (#526D82) */
            color: #fff !important; /* Warna teks tombol (putih) */
            border-color: #fff !important; /* Warna border tombol (putih) */
        }

        /* Aturan CSS untuk mengubah warna teks tombol saat dihover */
        .btn-outline-light:hover {
            color: #000 !important; /* Warna teks menjadi hitam saat dihover */
        }

        .btn-warning:hover {
            color: #000 !important; /* Warna teks tombol Sign-up menjadi hitam saat dihover */
        }

        #mainMenu li > a:hover::before,
        #mainMenu li > a.active::before {
            -webkit-transform: scale(1, 1);
            -ms-transform: scale(1, 1);
            transform: scale(1, 1);
            -webkit-transform-origin: left center;
            -ms-transform-origin: left center;
            transform-origin: left center;
        }

        [data-target="#mainMenu"] {
            position: relative;
            z-index: 999;
          }
          
          #mainMenu li > a {
            font-size: 12px;
            letter-spacing: 1px;
            color: #fff;
            font-weight: 400;
            position: relative;
            z-index: 1;
            text-decoration: none;
          }
          
          #mainMenu li > a {
            color: #fff;
            text-decoration: none;
          }
          
          #mainMenu li:not(:last-of-type) {
            margin-right: 30px;
          }
          
          #mainMenu li > a::before {
            position: absolute;
            content: "";
            width: calc(100% - 1px);
            height: 1px;
            background: #fff;
            bottom: -6px;
            left: 0;
            -webkit-transform: scale(0, 1);
            -ms-transform: scale(0, 1);
            transform: scale(0, 1);
            -webkit-transform-origin: right center;
            -ms-transform-origin: right center;
            transform-origin: right center;
            z-index: -1;
          
            -webkit-transition: transform 0.5s ease;
            transition: transform 0.5s ease;
          }

          .highlighted-text {
            color: #FFC200 !important;
        }
        /* Set the background color for the entire HTML */
    </style>
{% endblock meta %}
<body>
{% block content %}
  <header class="p-2 navbar-bg-dark"> <!-- Menggunakan warna latar belakang navbar dari Bootstrap -->
    <div>
      <div class="d-flex flex-wrap align-items-center justify-content-between justify-content-lg-start">
        <a href="/" class="d-flex align-items-foreground mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>
    
        <ul class="nav col-12 col-lg-auto mb-2 justify-content-center mb-md-0" id="mainMenu">
            <svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
              <image x="0" y="0" width="50" height="50" xlink:href="{% static 'images/Logo.svg' %}">
            </svg>
            <li class="nav-item" style="margin-left:20px;"><a href="{% url "lend:show_catalog" %}" id="nav-text2" class="nav-link px-2 text">Catalog</a></li>
            <li class="nav-item" style="margin-left:20px;"><a href="{% url "review:show_main" %}" id="nav-text3" class="nav-link px-2 text">Review Book</a></li>
            <li class="nav-item" style="margin-left:20px;"><a href="{% url "quote:quotes_page"%}" id="nav-text4" class="nav-link px-2 text">Quotes</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 ml-auto" action="{% url 'book:searchbar' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
              <input type="text" id="search" class="form-control form-control-dark" placeholder="Search books" aria-label="Search" name="searched">
              <button type="submit" class="btn btn-outline-light">Search</button> <!-- Menggunakan kelas Bootstrap untuk tombol -->
            </div>
          </form>
        
          <a href="{% url "book:login" %}"><button type="" class="btn btn-outline-light">Logout</button></a>
      
       
      </div>
    </div>
  </header>
{% endblock content %}
<script>
    {% comment %} var currentURL1 = window.location.pathname;
    var targetURL1 = "";
    var targetURL2 = "review/";
    var targetURL3 = "";
    var targetURL4 = "";
    var targetURL5 = "";
    var navText1 = document.getElementById("nav-text1");
    var navText2 = document.getElementById("nav-text2");
    var navText3 = document.getElementById("nav-text3");
    var navText4 = document.getElementById("nav-text4");
    var navText5 = document.getElementById("nav-text5");
    if (currentURL === targetURL1) {
        navText1.classList.add("highlighted-text");
    }
    if (currentURL === targetURL2) {
        navText2.classList.add("highlighted-text");
    }
    if (currentURL === targetURL3) {
        navText3.classList.add("highlighted-text");
    }
    if (currentURL === targetURL4) {
        navText3.classList.add("highlighted-text");
    }
    if (currentURL === targetURL5) {
        navText3.classList.add("highlighted-text");
    } {% endcomment %}
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"></script>